### PR TITLE
ExcelWorkbook::count() type int

### PR DESCRIPTION
**Pull request by ua0leg**
Fix for 
Return type of Svrnm\ExcelDataTables\ExcelWorkbook::count() should either be compatible with Countable::count()

### CODE REVIEW

**Comment by svrnm** [comment]
Thank you @ua0leg

**Comment by svrnm** [comment]
@ua0leg let me know if you use the v0.2.x I can create a release to v0.2.3

**Comment by ua0leg** [comment]
Thanks for your merge!
@svrnm I'm using version : * dev-master, v0.2.2

**Comment by svrnm** [comment]
FYI, https://github.com/svrnm/exceldatatables/releases/tag/v0.2.3

**Comment by svrnm** [comment]
I just recognized that adding this PR to the code is a breaking change, it affects PHP <7 which people shouldn't use anyways but to stay true to semconv, let me do the following: 

* Undo your PR
* Release v0.2.4
* Re-apply your PR
* Release v0.3.0

Apologies, I have not worked on this code base for years so I need to get used to it myself once again

**Pull request merged**
